export default {
  STACK__PRE_LOGIN: 'STACK_PRE_LOGIN',
  STACK__POST_LOGIN: 'STACK_POST_LOGIN',
  ROUTE_SIGNIN: 'R_SIGNIN',
  ROUTE_SIGNUP: 'R_SIGNUP',
  ROUTE_SIGNUP_SUCCESS: 'R_SIGNUP_SUCCESS',
  ROUTE_DASHBOARD: 'R_DASHBOARD',
  ROUTE_WEBVIEW: 'R_WEBVIEW',
};
